# Generated by Django 4.1.7 on 2023-04-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='total_sales',
            new_name='total_sale',
        ),
    ]
