# Generated by Django 4.1.7 on 2023-04-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_item_categories_item_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categories',
            new_name='category',
        ),
    ]
